/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databese;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author R. TAHA
 */
public class Doctors_entry extends javax.swing.JFrame {

    /**
     * Creat ves new form Doctors_entry
     */
    public Doctors_entry() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("login ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 210, 100, 29);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 100, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Doctor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(144, 110, 40, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 160, 60, 14);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "welcome doctor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 30, 300, 26);

        jButton2.setFont(new java.awt.Font("Arabic Typesetting", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Sifre degistirme\n\n");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(223, 210, 100, 30);

        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(230, 150, 110, 30);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 30, 51, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databese/1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "yonlerndirilyor");
        new Sefir_degistirme().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                if (jTextField1.getText().isEmpty() || jPasswordField2.getText().isEmpty()) {
                    
                    throw new nullleave("lutfen bos birakmayiniz");
                    
                } else {
                    if (Name(jTextField1.getText()) && password(jPasswordField2.getText())) {
                        JOptionPane.showMessageDialog(this, "welcome doctor   " + jTextField1.getText()+" ");
                        switch (jTextField1.getText()) {
                            case "ak":
                                new doktur1().setVisible(true);
                                break;
                            case "yusuf":
                                new doktur2().setVisible(true);
                                break;
                            default:
                                new doktur3().setVisible(true);
                                break;
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "we have a something rong");
                    }
                }
            } catch (nullleave ex) {
              JOptionPane.showMessageDialog(this, ex);
            }
            jTextField1.setText(null);
            jPasswordField2.setText(null);
        }
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Hastahane().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    public boolean Name(String adi) {
        try {
            Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            String theid = "SELECT * FROM DOKTURLAR WHERE ADI='" + adi + "'";
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(theid);
            while (rs.next()) {
                return rs.getString(3).equals(adi);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Doctors_entry.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    public boolean password(String sefir) {
        try {
            Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            String theid = "SELECT * FROM DOKTURLAR WHERE SEFIR='" + sefir + "'";
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(theid);
            while (rs.next()) {
                return rs.getString(4).equals(sefir);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Doctors_entry.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctors_entry.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctors_entry.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctors_entry.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctors_entry.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctors_entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
