/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databese;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author R. TAHA
 */
public class doktur1 extends javax.swing.JFrame {
    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("Ali_nazimPU");
    EntityManager em = emf.createEntityManager();
    DefaultListModel dlm = new DefaultListModel();
    DefaultTableModel dtm = new DefaultTableModel();
    FileWriter fileWriter = null;
    BufferedWriter bufferedWriter = null;
    Scanner scanner = null;
    FileReader fileReader = null;
    BufferedReader bufferedReader = null;
    Connection connection = null;
    PreparedStatement preparedStatement = null;
    Statement statement = null;
    ResultSet resultSet = null;
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();

    /**
     * Creates new form doktor
     */
    public doktur1() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            jList1.setModel(dlm);
            jTable1.setModel(dtm);
            Query doktorQuery = em.createQuery("SELECT d FROM Dokturlar d");
            List<Dokturlar> dokturlar = doktorQuery.getResultList();
            for (Dokturlar dokturlistesi : dokturlar) {
               if (dokturlistesi.getAdi().equals("ak")) {
                    dlm.addElement(null);
                } else {
                    dlm.addElement(dokturlistesi.getAdi());
                }
            }
            jcomebox.removeAllItems();
            dtm.setColumnIdentifiers(new Object[]{"ID", "NAME", "SURNAME", "DAYS", "DOKTOR", "GENDER", "HORUS","disease"});
            //----------------------------------------------------------------------------
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            String Akmesaji = "SELECT * FROM MESAJ WHERE GONDERILEN='ak'";
            Statement gosterici = connection.createStatement();
            resultSet = gosterici.executeQuery(Akmesaji);
            while (resultSet.next()) {
                mesaj_gostermek.append("Saat  :" + resultSet.getString("ZAMAN")
                        + "      alici : " + resultSet.getString("ALICI") + "   "
                        + " mesaj: "
                        + resultSet.getString("MESAJ") + "\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(doktur1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jcomebox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtdosya = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmesajyaz = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        mesaj_gostermek = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtdosya_arama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        gelen_mesaj = new javax.swing.JTextArea();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 600));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 290, 620, 280);

        jButton1.setText("Hasta bilgiler goster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 140, 390, 40);

        jButton2.setText("sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 190, 390, 40);

        jcomebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcomebox);
        jcomebox.setBounds(10, 50, 390, 30);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(740, 110, 130, 130);

        jButton4.setText("dosya yazdir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(740, 240, 140, 32);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(620, 320, 490, 260);
        getContentPane().add(txtdosya);
        txtdosya.setBounds(560, 240, 170, 30);

        jButton5.setText("dosyadaki  goster");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(640, 280, 280, 33);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("dosya Adi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 210, 110, 20);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Doktorlar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(640, 120, 93, 18);

        jLabel3.setText("Hastalar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 50, 90, 14);
        getContentPane().add(txtmesajyaz);
        txtmesajyaz.setBounds(750, 10, 110, 60);

        mesaj_gostermek.setColumns(20);
        mesaj_gostermek.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mesaj_gostermek.setForeground(new java.awt.Color(255, 0, 0));
        mesaj_gostermek.setRows(5);
        jScrollPane4.setViewportView(mesaj_gostermek);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(870, 10, 360, 100);

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("masej");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 10, 80, 20);

        jButton6.setText("hastalar goster");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 90, 390, 40);

        jButton8.setText("tüm hastaları bilgilerini göster");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(460, 40, 240, 30);

        jButton9.setText("gonder");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(760, 80, 100, 23);
        getContentPane().add(txtdosya_arama);
        txtdosya_arama.setBounds(920, 280, 180, 40);

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("dosya Adi");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1100, 300, 100, 14);

        jButton10.setText("dosya arama");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(920, 240, 160, 40);

        gelen_mesaj.setColumns(20);
        gelen_mesaj.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        gelen_mesaj.setForeground(new java.awt.Color(0, 0, 204));
        gelen_mesaj.setRows(5);
        jScrollPane5.setViewportView(gelen_mesaj);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(870, 110, 360, 100);

        jButton11.setText("gelen masejler");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(1089, 210, 140, 23);

        jButton12.setText("exit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(20, 10, 80, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databese/f4.jpg"))); // NOI18N
        jLabel5.setText("tum hastalari goster");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1250, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            String hastalar_doldurme = "SELECT * FROM RENDEVU WHERE DOKTOR='ak'";
            statement = connection.createStatement();
            resultSet = statement.executeQuery(hastalar_doldurme);
            while (resultSet.next()) {
                String hastalar = resultSet.getString("Name");
                jcomebox.addItem(hastalar);
            }
            JOptionPane.showMessageDialog(this, "hastalariniz eklendi");
            jcomebox.setSelectedIndex(0);
        } catch (SQLException ex) {
            Logger.getLogger(doktur1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Query hastaq = em.createQuery("SELECT p FROM Rendevu p WHERE p.name=:tc");
        em.clear();
        hastaq.setParameter("tc", jcomebox.getSelectedItem());
        List<Rendevu> rendevu = hastaq.getResultList();
        int count = 0;
        for (Rendevu rendevular : rendevu) {
            for (int i = 0; i <  rendevu.size(); i++) {
                if (rendevular.getDoktor().equals("ak")) {
                    dtm.addRow(new Object[]{rendevular.getId(),rendevular.getName(),rendevular.getSurname(),rendevular.getDays(),rendevular.getDoktor(),rendevular.getGender()
                    ,rendevular.getHorus(),"kalip"});
                    JOptionPane.showMessageDialog(this, "sectiginiz Hasta.." + jcomebox.getSelectedItem());
                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "Hastanin bilgileri bulunmadi");
                    break;
                }
            }
            break;
        }
        JOptionPane.showMessageDialog(this, "sectiginiz Hasta.." + jcomebox.getSelectedItem());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
        Rendevu rendevu =new Rendevu();
       Query rendevuq =em.createQuery("DELETE FROM Rendevu p WHERE p.id=:id");
       rendevuq.setParameter("id",jTable1.getValueAt(jTable1.getSelectedRow(),0));
       em.getTransaction().begin();
       rendevuq.executeUpdate();
       em.getTransaction().commit();
       JOptionPane.showMessageDialog(this,jcomebox.getSelectedItem()+"has been deleted");
      }catch(ArrayIndexOutOfBoundsException e){
       JOptionPane.showMessageDialog(this,"Please select the patient");
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Query hastalarq = em.createQuery("SELECT p FROM Rendevu p WHERE p.doktor='ak'");
        dtm.setRowCount(0);
        List<Rendevu> rendevu_listesi = hastalarq.getResultList();
        for (Rendevu rendevular : rendevu_listesi) {
            dtm.addRow(new Object[]{rendevular.getId(),rendevular.getName(),rendevular.getSurname(),rendevular.getDays(),rendevular.getDoktor(),rendevular.getGender()
                    ,rendevular.getHorus(),"kalip"});
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            // TODO add your handling code here:
            if (txtmesajyaz.equals("") || txtmesajyaz.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "lutefn gondereceginiz kisiyi yaziniz ya de mseajiniz bos birakmayiniz");
            } else {
                connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
                String gondelien = "INSERT INTO MESAJ (GONDERILEN,MESAJ,ALICI,ZAMAN)VALUES (?,?,?,?)";
                PreparedStatement prepareStatement1 = connection.prepareStatement(gondelien);
                DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm");
                Date zaman = new Date();
                prepareStatement1.setString(1, "ak");
                prepareStatement1.setString(2, txtmesajyaz.getText());
                prepareStatement1.setString(3, (String) jList1.getSelectedValue());
                prepareStatement1.setString(4, df.format(zaman));
                prepareStatement1.executeUpdate();
                JOptionPane.showMessageDialog(this, "mesajiniz   " + jList1.getSelectedValue() + "  gonderildi");
                String Akmesaji = "SELECT * FROM MESAJ WHERE GONDERILEN='ak'";
                Statement gosterici = connection.createStatement();
                resultSet = gosterici.executeQuery(Akmesaji);
                while (resultSet.next()) {
                    mesaj_gostermek.append("Saat  :" + resultSet.getString("ZAMAN")
                            + "      alici : " + resultSet.getString("ALICI") + "   "
                            + " mesaj: "
                            + resultSet.getString("MESAJ") + "\n");
                    txtmesajyaz.setText(null);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(doktur1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            if (txtdosya.getText().equals("") || txtdosya.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "lutfen  bos birakmayiniz");
            } else {
                fileWriter = new FileWriter("C:\\Users\\R. TAHA\\Desktop\\Hasta bilgileri\\" + txtdosya.getText());
                bufferedWriter = new BufferedWriter(fileWriter);
                Query hastaq = em.createQuery("SELECT p FROM Hasta p");
                List<Hasta> hastlar = hastaq.getResultList();
                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                    bufferedWriter.write(jTable1.getColumnName(i));
                    bufferedWriter.write("\t");
                }
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    bufferedWriter.newLine();
                    for (int j = 0; j < jTable1.getColumnCount(); j++) {
                        bufferedWriter.write(String.valueOf(jTable1.getValueAt(i, j)));
                        bufferedWriter.write("\t");
                    }
                    bufferedWriter.flush();
                    bufferedWriter.close();
                    fileWriter.close();
                    JOptionPane.showMessageDialog(this, txtdosya.getText() + " dosyaniz yazildi");
                }
                
                txtdosya.setText(null);
            }
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            if (txtdosya_arama.getText().equals("") || txtdosya_arama.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "lutfen gostereceginiz dosya adini yaziniz");
            } else {
                String s = txtdosya_arama.getText();
                System.out.println("1"+s);
                String temp = "";
                
                for (int i = 0; i < s.length(); i++) {
                    if(s.charAt(i) == 92){
                        temp += s.substring(0, i) + "\\\\";
                        s = s.substring(s.indexOf((char) 92) + 1);
                    }
                }
                temp += s;
                
                System.out.println("2"+temp);
                System.out.println("3"+s);
                fileReader = new FileReader(txtdosya_arama.getText());
                bufferedReader = new BufferedReader(fileReader);
                String S = " ";
                while ((S = bufferedReader.readLine()) != null) {
                    jTextArea1.append("\n" + S);
                }
                bufferedReader.close();
                fileReader.close();
            }

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "dosyaniz bulamadi");
        } catch (IOException ex) {
            Logger.getLogger(doktur1.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtdosya_arama.setText(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileSec = new JFileChooser();
        if (JFileChooser.APPROVE_OPTION == fileSec.showOpenDialog(this)) {
            File f = fileSec.getSelectedFile();
            txtdosya_arama.setText(f.getPath());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            // TODO add your handling code here:
            connection=DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            statement=connection.createStatement();
            resultSet=statement.executeQuery("SELECT MESAJ,ZAMAN,GONDERILEN FROM MESAJ WHERE ALICI='ak'");
            while (resultSet.next()) {                
                gelen_mesaj.append("\n"+"Saat: "+resultSet.getString("ZAMAN")+" gonderilen: "+resultSet.getString("GONDERILEN")+"  mesaj:"+resultSet.getString("MESAJ")+" ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(doktur1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String[] secimler={"Yes","No"};
        int secim=JOptionPane.showOptionDialog(this, "are you sure doctor ", "Exit", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, secimler, secimler[0]);
        if (secim==0) {
        JOptionPane.showMessageDialog(this,"See you again, doctor");
        new Doctors_entry().setVisible(true);
        this.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(this, "Welcome again doctor");
    
    
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktur1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea gelen_mesaj;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox jcomebox;
    private javax.swing.JTextArea mesaj_gostermek;
    private javax.swing.JTextField txtdosya;
    private javax.swing.JTextField txtdosya_arama;
    private javax.swing.JTextField txtmesajyaz;
    // End of variables declaration//GEN-END:variables
}
