/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databese;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author R. TAHA
 */
public class doktur3 extends javax.swing.JFrame {
   EntityManagerFactory emf = Persistence.createEntityManagerFactory("Ali_nazimPU");
    EntityManager em = emf.createEntityManager();
    DefaultListModel dlm = new DefaultListModel();
    DefaultTableModel dtm = new DefaultTableModel();
    FileWriter fileWriter = null;
    BufferedWriter bufferedWriter = null;
    Scanner scanner = null;
    FileReader fileReader = null;
    BufferedReader bufferedReader = null;
    Connection connection = null;
    PreparedStatement preparedStatement = null;
    Statement statement = null;
    ResultSet resultSet = null;
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();

    /**
     * Creates new form doktur3
     */
    public doktur3() {
       try {
           initComponents();
           this.setLocationRelativeTo(this);
           jList1.setModel(dlm);
           jTable1.setModel(dtm);
           jComboBox1.removeAllItems();
           dtm.setColumnIdentifiers(new Object[]{"ID", "NAME", "SURNAME", "DAYS", "DOKTOR", "GENDER", "HORUS", "disease"});
           Query doktorQuery = em.createQuery("SELECT d FROM Dokturlar d");
           List<Dokturlar> dokturlar = doktorQuery.getResultList();
           for (Dokturlar dokturlistesi : dokturlar) {
               if (dokturlistesi.getAdi().equals("mahmut")) {
                   dlm.addElement(null);
               } else {
                   dlm.addElement(dokturlistesi.getAdi());
               }
           }
           //------------------------------------------------------------------------------
           connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
           String yusufmesaji = "SELECT * FROM MESAJ WHERE GONDERILEN='mahmut'";
           Statement gosterici = connection.createStatement();
           resultSet = gosterici.executeQuery(yusufmesaji);
           while (resultSet.next()) {
               gonderilen.append("Date :" + resultSet.getString("ZAMAN")
                       + "      receiver : " + resultSet.getString("ALICI") + "   "
                       + " message: "
                       + resultSet.getString("MESAJ") + "\n");
           }
       } catch (SQLException ex) {
           Logger.getLogger(doktur3.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
        

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filename = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtmesajyaz = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        gonderilen = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        gelen_mesaj = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        filetxt = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1290, 584));
        getContentPane().setLayout(null);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 11, 90, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 50, 230, 30);

        jButton2.setText("Patients");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 80, 290, 40);

        jButton3.setText("Show patient information");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 120, 290, 40);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 160, 290, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 560, 402);

        filename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filenameActionPerformed(evt);
            }
        });
        getContentPane().add(filename);
        filename.setBounds(390, 140, 130, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("File Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 110, 70, 14);

        jButton6.setText("File name");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(540, 140, 230, 30);

        jButton7.setText("Show all patient information");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(330, 40, 240, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(570, 260, 490, 330);
        getContentPane().add(txtmesajyaz);
        txtmesajyaz.setBounds(870, 10, 100, 70);

        gonderilen.setColumns(20);
        gonderilen.setFont(new java.awt.Font("Arabic Typesetting", 0, 18)); // NOI18N
        gonderilen.setRows(5);
        jScrollPane3.setViewportView(gonderilen);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(970, 0, 310, 100);

        gelen_mesaj.setColumns(20);
        gelen_mesaj.setFont(new java.awt.Font("Arabic Typesetting", 0, 18)); // NOI18N
        gelen_mesaj.setRows(5);
        jScrollPane4.setViewportView(gelen_mesaj);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(970, 100, 310, 90);

        jButton8.setText("Sent");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(740, 33, 110, 30);

        jButton9.setText("Show me messages");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(1060, 190, 220, 30);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList1);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(870, 80, 100, 100);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doctor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(794, 120, 60, 14);
        getContentPane().add(filetxt);
        filetxt.setBounds(820, 230, 250, 30);

        jButton10.setText("Show me the information on the file");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(580, 230, 240, 30);

        jButton11.setText("File search");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(820, 200, 220, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Patients");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 60, 70, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databese/21522124751_77637cace8_k.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(4, 4, 1270, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filenameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
           String[] secimler={"Yes","No"};
        int secim=JOptionPane.showOptionDialog(this, "are you sure doctor ", "Exit", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, secimler, secimler[0]);
        if (secim==0) {
        JOptionPane.showMessageDialog(this,"See you again, doctor");
        new Doctors_entry().setVisible(true);
        this.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(this, "Welcome again doctor");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            String hastalar_doldurme = "select * from RENDEVU WHERE DOKTOR='mahmut'";
            statement = connection.createStatement();
            resultSet = statement.executeQuery(hastalar_doldurme);
            while (resultSet.next()) {
                String hastalar = resultSet.getString("NAME");
                jComboBox1.addItem(hastalar);
            }
            JOptionPane.showMessageDialog(this, "Your patients have been added");
            jComboBox1.setSelectedIndex(0);
        } catch (SQLException ex) {
            Logger.getLogger(doktur1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           Query hastaq = em.createQuery("SELECT p FROM Rendevu p WHERE p.name=:tc");
        em.clear();
        hastaq.setParameter("tc", jComboBox1.getSelectedItem());
        List<Rendevu> rendevu = hastaq.getResultList();
        int count = 0;
        for (Rendevu rendevular : rendevu) {
            for (int i = 0; i <  rendevu.size(); i++) {
                if (rendevular.getDoktor().equals("mahmut")) {
                    dtm.addRow(new Object[]{rendevular.getId(),rendevular.getName(),rendevular.getSurname(),rendevular.getDays(),rendevular.getDoktor(),rendevular.getGender()
                    ,rendevular.getHorus(),"beyin"});
                    JOptionPane.showMessageDialog(this, "sectiginiz Hasta.." + jComboBox1.getSelectedItem());
                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "Hastanin bilgileri bulunmadi");
                    break;
                }
            }
            break;
        }
        JOptionPane.showMessageDialog(this, "sectiginiz Hasta.." + jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            String hasta_silme = "DELETE FROM RENDEVU WHERE ID=?";
            preparedStatement = connection.prepareStatement(hasta_silme);
            preparedStatement.setInt(1, (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            int silinen = preparedStatement.executeUpdate();
            dtm.removeRow(jTable1.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Patient " + jComboBox1.getSelectedItem() + "  deleted");
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,"Please select the patient");
        } catch(ArrayIndexOutOfBoundsException e){
         JOptionPane.showMessageDialog(this,"Please select the patient");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try {
           connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            String hastalar = "select * from RENDEVU where doktor='mahmut'";
            Statement hastaStatement = connection.createStatement();
            ResultSet rsh = hastaStatement.executeQuery(hastalar);
               dtm.setRowCount(0);
            while (rsh.next()) {                
                dtm.addRow(new Object[]{rsh.getInt(1), rsh.getString(2), rsh.getString(3), rsh.getString(4), rsh.getString(5), rsh.getString(6), rsh.getString(7), "beyin"});
            }
        } catch (SQLException ex) {
            Logger.getLogger(doktur2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            if (filename.getText().equals("") || filename.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Do not leave empty");
            } else {
                fileWriter = new FileWriter("C:\\Users\\R. TAHA\\Desktop\\Hasta bilgileri\\" + filename.getText()+".txt");
                bufferedWriter = new BufferedWriter(fileWriter);
                Query hastaq = em.createQuery("SELECT p FROM Hasta p");
                List<Hasta> hastlar = hastaq.getResultList();
                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                    bufferedWriter.write(jTable1.getColumnName(i));
                    bufferedWriter.write("\t");
                }
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    bufferedWriter.newLine();
                    for (int j = 0; j < jTable1.getColumnCount(); j++) {
                        bufferedWriter.write(String.valueOf(jTable1.getValueAt(i, j)));
                        bufferedWriter.write("\t");
                    }
                    bufferedWriter.flush();
                    bufferedWriter.close();
                    fileWriter.close();
                    JOptionPane.showMessageDialog(this, filename.getText() + " Your file was written");
                }
                filename.setText(null);
            }
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            if (filetxt.getText().equals("") || filetxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "lutfen gostereceginiz dosya adini yaziniz");
            } else {
                fileReader = new FileReader(filetxt.getText());
                bufferedReader = new BufferedReader(fileReader);
                String S = " ";
                while ((S = bufferedReader.readLine()) != null) {
                    jTextArea1.append("\n" + S);
                }
                bufferedReader.close();
                fileReader.close();
            }

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Your file is not found");
        } catch (IOException ex) {
            Logger.getLogger(doktur1.class.getName()).log(Level.SEVERE, null, ex);
        }
        filetxt.setText(null);
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
          JFileChooser fileSec = new JFileChooser();
        if (JFileChooser.APPROVE_OPTION == fileSec.showOpenDialog(this)) {
            File f = fileSec.getSelectedFile();
            filetxt.setText(f.getPath());
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            connection=DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            statement=connection.createStatement();
            resultSet=statement.executeQuery("SELECT MESAJ,ZAMAN,GONDERILEN FROM MESAJ WHERE ALICI='mahmut'");
            while (resultSet.next()) {                
                gelen_mesaj.append("\n"+"Date: "+resultSet.getString("ZAMAN")+" receiver: "+resultSet.getString("GONDERILEN")+"  message:"+resultSet.getString("MESAJ")+" ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(doktur1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         try {

            if (txtmesajyaz.equals("") || txtmesajyaz.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "lutefn gondereceginiz kisiyi yaziniz ya de mseajiniz bos birakmayiniz");
            } else {
                connection = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
                String gondelien = "INSERT INTO MESAJ (GONDERILEN,MESAJ,ALICI,ZAMAN)VALUES (?,?,?,?)";
                PreparedStatement prepareStatement1 = connection.prepareStatement(gondelien);
                DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm");
                Date zaman = new Date();
                prepareStatement1.setString(1, "mahmut");
                prepareStatement1.setString(2, txtmesajyaz.getText());
                prepareStatement1.setString(3, (String) jList1.getSelectedValue());
                prepareStatement1.setString(4, df.format(zaman));
                prepareStatement1.executeUpdate();
                JOptionPane.showMessageDialog(this, "Your message   " + jList1.getSelectedValue() + "  sent");
                String mahmutmesaji = "SELECT * FROM MESAJ WHERE GONDERILEN='mahmut'";
                Statement gosterici = connection.createStatement();
                resultSet = gosterici.executeQuery(mahmutmesaji);
                while (resultSet.next()) {
                    gonderilen.append("Date :" + resultSet.getString("ZAMAN")
                            + "      receiver : " + resultSet.getString("ALICI") + "   "
                            + " message: "
                            + resultSet.getString("MESAJ") + "\n");
                    txtmesajyaz.setText(null);
                      }
            }
        } catch (SQLException ex) {
            Logger.getLogger(doktur1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktur3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktur3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktur3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktur3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktur3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filename;
    private javax.swing.JTextField filetxt;
    private javax.swing.JTextArea gelen_mesaj;
    private javax.swing.JTextArea gonderilen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtmesajyaz;
    // End of variables declaration//GEN-END:variables
}
