/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databese;

import databese.kontur_erken;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.derby.client.am.SQLExceptionFactory40;

/**
 *
 * @author R. TAHA
 */
public class kayit_yaptima extends javax.swing.JFrame {

   // ImageIcon ic = new ImageIcon("C:\\Users\\R. TAHA\\Documents\\NetBeansProjects\\JDBC5\\src\\ENTTIP\\image.jpg");

    /**
     * Creates new form kayit_yaptima
     */
    public kayit_yaptima() {
        initComponents();
    //    fotograf.setIcon(ic);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kayit_yaptima = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jtc_kimlik = new javax.swing.JLabel();
        jsifre = new javax.swing.JLabel();
        jcep_tel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 500));
        getContentPane().setLayout(null);
        getContentPane().add(ID);
        ID.setBounds(270, 130, 150, 30);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 140, 70, 20);

        kayit_yaptima.setText("register");
        kayit_yaptima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayit_yaptimaMouseClicked(evt);
            }
        });
        kayit_yaptima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayit_yaptimaActionPerformed(evt);
            }
        });
        getContentPane().add(kayit_yaptima);
        kayit_yaptima.setBounds(240, 330, 190, 40);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("password ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 250, 70, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Adi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 200, 70, 20);
        getContentPane().add(Name);
        Name.setBounds(270, 190, 150, 30);

        jtc_kimlik.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        getContentPane().add(jtc_kimlik);
        jtc_kimlik.setBounds(460, 130, 180, 30);

        jsifre.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        getContentPane().add(jsifre);
        jsifre.setBounds(430, 260, 180, 20);
        getContentPane().add(jcep_tel);
        jcep_tel.setBounds(450, 200, 170, 20);
        getContentPane().add(password);
        password.setBounds(270, 250, 150, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 20, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kayit_yaptimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayit_yaptimaMouseClicked
        // TODO add your handling code here:
    

    }//GEN-LAST:event_kayit_yaptimaMouseClicked

    private void kayit_yaptimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayit_yaptimaActionPerformed
           try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            
            String s = "INSERT INTO HASTA (ID,ADI,SIFRE)VALUES (?,?,?)";
            PreparedStatement stmtp = con.prepareStatement(s);
            Pattern p = Pattern.compile("\\d");
            Matcher mp = p.matcher(ID.getText());           
            if (mp.find()) {
                jtc_kimlik.setForeground(Color.GREEN);
                jtc_kimlik.setText("Tamam");
                stmtp.setInt(1, Integer.parseInt(ID.getText()));
            } else {
                jtc_kimlik.setForeground(Color.red);
                jtc_kimlik.setText("Lutfen gecli numara giriniz");
            }
            ID.setText(null);
          Pattern p4 = Pattern.compile("[a-z]");
            Matcher mp4 = p4.matcher(Name.getText());
            if (mp4.find()) {
                jcep_tel.setForeground(Color.GREEN);
                jcep_tel.setText("Tamam");
                stmtp.setString(2, Name.getText());
            } else {
                jcep_tel.setForeground(Color.red);
                jcep_tel.setText("Lutfen gecli adi giriniz");
            }
            Name.setText(null);
            Pattern p1 = Pattern.compile("\\d");
            Matcher mp1 = p1.matcher(password.getText());
            if (mp1.find()) {
                jsifre.setForeground(Color.GREEN);
                jsifre.setText("Tamam");
                stmtp.setString(3, password.getText());
            } else {
                jsifre.setForeground(Color.red);
                jsifre.setText("you  password very woke");
            }
            password.setText(null);
            stmtp.executeUpdate();
             JOptionPane.showMessageDialog(null, "successful registration");
            new kontur_erken().setVisible(true);
        } catch (SQLException ex) {
            
        }
      
    }//GEN-LAST:event_kayit_yaptimaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new kontur_erken().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayit_yaptima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayit_yaptima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayit_yaptima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayit_yaptima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayit_yaptima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jcep_tel;
    private javax.swing.JLabel jsifre;
    private javax.swing.JLabel jtc_kimlik;
    private javax.swing.JToggleButton kayit_yaptima;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
