/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databese;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author R. TAHA
 */
public class kontur_erken extends javax.swing.JFrame {
   static int kullanci=0; 
    /**
     * Creates new form jfarme
     */
    public kontur_erken() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        giris_buton = new javax.swing.JButton();
        kayit_yapma = new javax.swing.JButton();
        txtsefir_islemi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        giris_buton.setText("login ");
        giris_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_butonActionPerformed(evt);
            }
        });
        getContentPane().add(giris_buton);
        giris_buton.setBounds(100, 320, 190, 40);

        kayit_yapma.setText("register");
        kayit_yapma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayit_yapmaActionPerformed(evt);
            }
        });
        getContentPane().add(kayit_yapma);
        kayit_yapma.setBounds(300, 320, 190, 40);

        txtsefir_islemi.setText("Change password");
        txtsefir_islemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsefir_islemiActionPerformed(evt);
            }
        });
        getContentPane().add(txtsefir_islemi);
        txtsefir_islemi.setBounds(500, 320, 190, 40);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(194, 180, 90, 40);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 230, 110, 40);

        ID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(ID);
        ID.setBounds(339, 180, 140, 40);
        getContentPane().add(password);
        password.setBounds(341, 230, 140, 40);

        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 49, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void giris_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_butonActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/TAHA", "TAHA", "TAHA");
            String s = "SELECT * FROM Hasta WHERE ID=? AND SIFRE=?";
            PreparedStatement stmtp = con.prepareStatement(s);
            kullanci=Integer.parseInt(ID.getText());
            stmtp.setInt(1,Integer.valueOf(kullanci));
            stmtp.setInt(2, Integer.valueOf(password.getText()));
            ResultSet rs = stmtp.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "WELCOME");
                new Hasta_olusturmek().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "You have entered the wrong information");
            }
            ID.setText(null);
            password.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(kontur_erken.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please fill in the information in the spaces");
        }
    }//GEN-LAST:event_giris_butonActionPerformed

    private void kayit_yapmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayit_yapmaActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new kayit_yaptima().setVisible(true);
    }//GEN-LAST:event_kayit_yapmaActionPerformed

    private void txtsefir_islemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsefir_islemiActionPerformed
        // TODO add your handling code here:
            new sefre_degistirme().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_txtsefir_islemiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Hastahane().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kontur_erken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kontur_erken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kontur_erken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kontur_erken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kontur_erken().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton giris_buton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton kayit_yapma;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton txtsefir_islemi;
    // End of variables declaration//GEN-END:variables
}
