/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyal.medya;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static sosyal.medya.login_System.username;

/**
 *
 * @author yusuf
 */
public class message extends javax.swing.JFrame {

    /**
     * Creates new form message
     */
    static String newLine = "\n";

    public message() {
        initComponents();
        jTxtAreaChat.setVisible(false);
        jTxtAreaInput.setVisible(false);
        jBtnSend.setVisible(false);
        jListFollowing.setVisible(false);
        jTxtAreaChat.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane4.setVisible(false);
        jScrollPane3.setVisible(false);
        jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jUserPassword = new javax.swing.JPasswordField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtAreaChat = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaInput = new javax.swing.JTextArea();
        jBtnSend = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnDisconnect = new javax.swing.JButton();
        jBtnConnect = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListFollowing = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User name");

        jTxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUserNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        jUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserPasswordActionPerformed(evt);
            }
        });

        jTxtAreaChat.setEditable(false);
        jTxtAreaChat.setColumns(20);
        jTxtAreaChat.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 14)); // NOI18N
        jTxtAreaChat.setForeground(new java.awt.Color(51, 51, 255));
        jTxtAreaChat.setRows(5);
        jScrollPane3.setViewportView(jTxtAreaChat);

        jTxtAreaInput.setColumns(20);
        jTxtAreaInput.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTxtAreaInput.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaInput);

        jBtnSend.setText("Send");
        jBtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSendActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("People you following");

        jBtnDisconnect.setText("Disconnect");
        jBtnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDisconnectActionPerformed(evt);
            }
        });

        jBtnConnect.setText("Connect");
        jBtnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConnectActionPerformed(evt);
            }
        });

        jListFollowing.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListFollowingValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jListFollowing);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jBtnSend)
                        .addGap(361, 361, 361))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtUserName)
                            .addComponent(jUserPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnDisconnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtnConnect)
                                .addComponent(jBtnDisconnect))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUserNameActionPerformed

    private void jUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserPasswordActionPerformed

    private void jBtnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConnectActionPerformed
        if (jTxtUserName.getText().isEmpty() || jUserPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "you must not leave it empty");
            return;
        }

        try {

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/test", "app", "app");
            Statement st = con.createStatement();
            String sql = "SELECT * FROM USERS";

            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                if (rs.getString(1).equals(jTxtUserName.getText()) && rs.getString(2).equals(jUserPassword.getText())) {
                    username = jTxtUserName.getText();
                    JOptionPane.showMessageDialog(this, "Done " + rs.getString(1));

                    //check new profile
                    String sql2 = "SELECT * FROM PROFILE WHERE USERNAME='" + username + "'";
                    rs = st.executeQuery(sql2);

                    if (rs.next()) {
                        jTxtAreaChat.setVisible(true);
                        jTxtAreaInput.setVisible(true);
                        jBtnSend.setVisible(true);
                        jListFollowing.setVisible(true);
                        jTxtAreaChat.setVisible(true);
                        jScrollPane1.setVisible(true);
                        jScrollPane4.setVisible(true);
                        jScrollPane3.setVisible(true);
                        jScrollPane1.setVisible(true);
                        jLabel2.setVisible(true);

                    }
                    // jlist following
                    String sql3 = "SELECT * FROM FRIEND WHERE USERNAME='" + username + "'";
                    ResultSet rs3 = st.executeQuery(sql3);
                    DefaultListModel model = new DefaultListModel();
                    while (rs3.next()) {
                        String following = rs3.getString("FRIEND");

                        model.addElement(following);
                    }

                    jListFollowing.setModel(model);

                    return;
                }
            }

            JOptionPane.showMessageDialog(this, "username or passwoed is wrong");

        } catch (SQLException e) {
            Logger.getLogger(login_System.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, e.getMessage());

        }

    }//GEN-LAST:event_jBtnConnectActionPerformed

    private void jBtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSendActionPerformed

        try {

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/test", "app", "app");
            Statement st = con.createStatement();

            //insert into message
            String sql4 = "insert into MESSAGE " + "(messageFrom,messageTo,message)" + "values(?,?,?)";
            PreparedStatement pst4 = con.prepareStatement(sql4);
            String to = jListFollowing.getSelectedValue().toString();
            if (jTxtAreaInput.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "you must write your message to send it");

            } else {
                pst4.setString(1, username);
                pst4.setString(2, to);
                pst4.setString(3, jTxtAreaInput.getText());
                pst4.executeUpdate();
            }

            //put message into jtxt area
            jListFollowingValueChanged(null);

        } catch (SQLException e) {
            Logger.getLogger(login_System.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, e.getMessage());

        }


    }//GEN-LAST:event_jBtnSendActionPerformed

    private void jListFollowingValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListFollowingValueChanged
        // TODO add your handling code here:
        jTxtAreaChat.setText(null);
        String selectedValue = jListFollowing.getSelectedValue().toString();

        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/test", "app", "app");

            Statement st = con.createStatement();

            //put message into jtxt area
            String sql5 = "SELECT * FROM MESSAGE WHERE MESSAGEFROM = '" + username + "' and MESSAGETO ='" + selectedValue 
                    + "' OR messagefrom = '" + selectedValue + "' and messageto='" + username + "'";
            ResultSet rs5 = st.executeQuery(sql5);

            while (rs5.next()) {
                jTxtAreaChat.append(rs5.getString("messagefrom") + " TO: " + rs5.getString("messageto") + ": " + rs5.getString("message") + newLine);

//                jTxtAreaChat.append("From " + username + " To: " + to + " : " + jTxtAreaInput.getText() + newLine);
                jTxtAreaInput.setText(null);
            }
        } catch (SQLException ex) {
            Logger.getLogger(message.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jListFollowingValueChanged

    private void jBtnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDisconnectActionPerformed
new Profile().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jBtnDisconnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new message().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConnect;
    private javax.swing.JButton jBtnDisconnect;
    private javax.swing.JButton jBtnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jListFollowing;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTxtAreaChat;
    private javax.swing.JTextArea jTxtAreaInput;
    private javax.swing.JTextField jTxtUserName;
    private javax.swing.JPasswordField jUserPassword;
    // End of variables declaration//GEN-END:variables
}
